# Generated by Django 5.1.3 on 2024-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
